# Generated by Django 4.2.30 on 2026-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_ai_observability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='coherence',
            field=models.CharField(default='moyenne', max_length=255),
        ),
    ]
